name: Execute tests with all Composer versions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        composer-version: [1.7.0, 2.0.0]
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.2 # Currently supported by all Composer versions
      - name: Set Composer version to specific version to test with
        run: composer require composer/composer:${{ matrix.composer-version }} --dev
      - name: Run Unit tests
        run: vendor/bin/phpunit --testsuite Unit
      - name: Run Functional tests
        run: vendor/bin/phpunit --testsuite Functional
