name: Execute tests with all Composer versions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        composer-version: [1.7.0, 2.0.0]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: Set Composer version to specific version to test with
        run: composer require composer/composer:${{ matrix.composer-version }} --dev
      - name: Run Unit tests
        run: vendor/bin/phpunit --testsuite Unit
      - name: Run Functional tests
        run: vendor/bin/phpunit --testsuite Functional
