name: Test all Composer versions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  get-all-available-composer-versions:
    runs-on: ubuntu-latest
    steps:
      - id: set-matrix
        run: |
          echo "::set-output name=matrix::$(composer show --format=json --all composer/composer | jq -c '{"composer-version":[.versions[] | select(test("^\\d+\\.\\d+\\.\\d+$"))] | sort_by(split(".") | map(tonumber)) | unique}')"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
  test:
    needs: get-all-available-composer-versions
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.get-all-available-composer-versions.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.2 # Currently supported by all Composer versions
          coverage: none
      - name: Set Composer version to specific version to test with
        run: composer self-update ${{ matrix.composer-version }}
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Run Unit tests
        run: vendor/bin/phpunit --testsuite Unit
      - name: Make new test folder outside the current project
        run: mkdir ../tests
      - name: Move functional test folder outside of project root so older versions of composer allow installation
        run: mv tests/* ../tests/
      - name: Point phpunit to the new test directory
        run: sed -i 's/>.\/tests/>..\/tests/' phpunit.xml.dist
      - name: Point the path repository strings in the scenario files to the new location
        run: |
          sed -i 's/"..\/..\/..\/"/"..\/..\/..\/composer-version-lock"/' ../tests/Functional/scenarios/clean-up.json
          sed -i 's/"..\/..\/..\/"/"..\/..\/..\/composer-version-lock"/' ../tests/Functional/scenarios/incorrect-suggested-version.json
          sed -i 's/"..\/..\/..\/"/"..\/..\/..\/composer-version-lock"/' ../tests/Functional/scenarios/no-version-set.json
          sed -i 's/"..\/..\/..\/"/"..\/..\/..\/composer-version-lock"/' ../tests/Functional/scenarios/passing-wildcard-version.json
          sed -i 's/"..\/..\/..\/"/"..\/..\/..\/composer-version-lock"/' ../tests/Functional/scenarios/wrong-version.json
      - name: Run Functional tests
        run: vendor/bin/phpunit --testsuite Functional
